# Generated by Django 2.1 on 2018-08-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180824_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Author Name'),
        ),
    ]
