# Generated by Django 2.1 on 2018-09-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180825_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='creation_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_logged_in',
            field=models.DateTimeField(blank=True),
        ),
    ]
