# Generated by Django 2.1 on 2018-09-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180914_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='date1',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='author',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_logged_in',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
